#
# Copyright 2023, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

[env]
SEL4_INCLUDE_DIRS = { value = "/opt/microkit/sdk/board/qemu_virt_aarch64/debug/include", relative = false }

[build]
target = "aarch64-sel4-microkit"
