#
# Copyright 2023, Colias Group, LLC
#
# SPDX-License-Identifier: BSD-2-Clause
#

[workspace]

resolver = "2"

members = [
    "cases/hello",
    "cases/serial-device",
    "cases/spawn-thread",
    "cases/spawn-task",
    "cases/spawn-task/child",
]
